require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

Rails:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Max: 120

Style/Documentation:
  Exclude:
    - "db/**/*"

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
